#!/bin/sh
DIR="$(cd "$(dirname "$0")" && pwd)"
export PATH="$DIR:$PATH"
export LD_LIBRARY_PATH="$DIR/lib64:$LD_LIBRARY_PATH"
export DYLD_LIBRARY_PATH="$DIR/lib64:$DYLD_LIBRARY_PATH"
if [ -f "$DIR/arut.jar" ]; then
    exec java -jar "$DIR/arut.jar" run
else
    echo "[ERROR] arut.jar not found."
fi
